os: linux
dist: trusty
language: node_js
before_install:
  - nvm install 0.10.28
  - nvm use 0.10.28
services:
  - mysql
  - redis
script:
  - npm install
  # uncomment for tests
  # - npm test
notifications:
  email: false
